# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded fidev_critcl 20050124.2 [list source [file join $dir fidev_critcl/tags/20050124/fidev_critcl.xotcl]]
package ifneeded fidev_database 20050124.1 [list source [file join $dir fidev_database/tags/20050124/fidev_database.xotcl]]
package ifneeded fidev_gpib_low_level 20040124 [list source [file join $dir fidev_gpib_low_level/tags/20050124/fidev_gpib_low_level.xotcl]]
package ifneeded fidev_ni488 20050124.1 [list source [file join $dir fidev_ni488/tags/20050124/fidev_ni488.xotcl]]
package ifneeded fidev_tcllib_md5 20050124.1 [list source [file join $dir fidev_tcllib_md5/tags/20050124/fidev_tcllib_md5.xotcl]]
