# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xomti_critcl 99991231.2 [list source [file join $dir xomti_critcl/trunk/xomti_critcl.xotcl]]
package ifneeded xomti_database 99991231.1 [list source [file join $dir xomti_database/trunk/xomti_database.xotcl]]
package ifneeded xomti_tcllib_md5 20050124.1 [list source [file join $dir xomti_tcllib_md5/tags/20050124/xomti_tcllib_md5.xotcl]]
package ifneeded xomti_tcllib_md5 99991231.1 [list source [file join $dir xomti_tcllib_md5/trunk/xomti_tcllib_md5.xotcl]]
package ifneeded TkDiff 4.0.2 [list source [file join $dir tkdiff/trunk/tkdiff.xotcl]]